name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Set up environment variables
        run: echo "API_KEY=${{ secrets.WATCH_WORTH_API_KEY }}" >> .env

      - name: Run automated tests
        run: npm test

      - name: Build the application
        run: npm run build

      - name: Start application for testing
        run: |
          npm start &
          sleep 30
          curl -f http://localhost:3000 || exit 1

      - name: Stop application
        run: pkill -f "node" || echo "No Node.js processes to kill"
